### PR TITLE
Dependency updates, clean ups and refactorings

### PR DESCRIPTION
**Pull request by dheid**
Hi @jamesward !

I updated the dependencies and tried to let the classes be more contract driven. I also did some performance tweaks and little code modernizations.

If you find the changes useful, don't hesitate do merge them.

Kind regards

Daniel

### CODE REVIEW

**Comment by jamesward** [comment]
Wow! This is amazing. Thank you sooo much!

**Comment by jamesward** [comment]
I'm releasing `0.49` now with these changes.

**Comment by jamesward** [comment]
Whoops. Release is failing and I'm not sure what the error means:
```
   [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.11:deploy (injected-nexus-deploy) on project webjars-locator-core: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.11:deploy failed: An API incompatibility was encountered while executing org.sonatype.plugins:nexus-staging-maven-plugin:1.6.11:deploy: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    extension>org.sonatype.plugins:nexus-staging-maven-plugin:1.6.11
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/home/jw/.m2/repository/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.11/nexus-staging-maven-plugin-1.6.11.jar
    [ERROR] urls[1] = file:/home/jw/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.11/nexus-common-1.6.11.jar
    [ERROR] urls[2] = file:/home/jw/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
    [ERROR] urls[3] = file:/home/jw/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
    [ERROR] urls[4] = file:/home/jw/.m2/repository/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
    [ERROR] urls[5] = file:/home/jw/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
    [ERROR] urls[6] = file:/home/jw/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
    [ERROR] urls[7] = file:/home/jw/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
    [ERROR] urls[8] = file:/home/jw/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar
    [ERROR] urls[9] = file:/home/jw/.m2/repository/com/google/errorprone/error_prone_annotations/2.7.1/error_prone_annotations-2.7.1.jar
    [ERROR] urls[10] = file:/home/jw/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
    [ERROR] urls[11] = file:/home/jw/.m2/repository/org/sonatype/nexus/nexus-client-core/2.14.21-02/nexus-client-core-2.14.21-02.jar
    [ERROR] urls[12] = file:/home/jw/.m2/repository/org/sonatype/nexus/plugins/nexus-restlet1x-model/2.14.21-02/nexus-restlet1x-model-2.14.21-02.jar
    [ERROR] urls[13] = file:/home/jw/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
    [ERROR] urls[14] = file:/home/jw/.m2/repository/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar
    [ERROR] urls[15] = file:/home/jw/.m2/repository/com/thoughtworks/xstream/xstream/1.4.15/xstream-1.4.15.jar
    [ERROR] urls[16] = file:/home/jw/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
    [ERROR] urls[17] = file:/home/jw/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
    [ERROR] urls[18] = file:/home/jw/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar
    [ERROR] urls[19] = file:/home/jw/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
    [ERROR] urls[20] = file:/home/jw/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar
    [ERROR] urls[21] = file:/home/jw/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
    [ERROR] urls[22] = file:/home/jw/.m2/repository/org/sonatype/sisu/siesta/siesta-client/1.8/siesta-client-1.8.jar
    [ERROR] urls[23] = file:/home/jw/.m2/repository/org/sonatype/sisu/siesta/siesta-common/1.8/siesta-common-1.8.jar
    [ERROR] urls[24] = file:/home/jw/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
    [ERROR] urls[25] = file:/home/jw/.m2/repository/com/sun/jersey/jersey-core/1.17.1/jersey-core-1.17.1.jar
    [ERROR] urls[26] = file:/home/jw/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
    [ERROR] urls[27] = file:/home/jw/.m2/repository/com/sun/jersey/jersey-client/1.17.1/jersey-client-1.17.1.jar
    [ERROR] urls[28] = file:/home/jw/.m2/repository/com/sun/jersey/contribs/jersey-apache-client4/1.17.1/jersey-apache-client4-1.17.1.jar
    [ERROR] urls[29] = file:/home/jw/.m2/repository/org/sonatype/sisu/siesta/siesta-jackson/1.8/siesta-jackson-1.8.jar
    [ERROR] urls[30] = file:/home/jw/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.6/jackson-annotations-2.12.6.jar
    [ERROR] urls[31] = file:/home/jw/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.6/jackson-core-2.12.6.jar
    [ERROR] urls[32] = file:/home/jw/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.6/jackson-databind-2.12.6.jar
    [ERROR] urls[33] = file:/home/jw/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.6/jackson-jaxrs-json-provider-2.12.6.jar
    [ERROR] urls[34] = file:/home/jw/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.12.6/jackson-jaxrs-base-2.12.6.jar
    [ERROR] urls[35] = file:/home/jw/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.12.6/jackson-module-jaxb-annotations-2.12.6.jar
    [ERROR] urls[36] = file:/home/jw/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar
    [ERROR] urls[37] = file:/home/jw/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar
    [ERROR] urls[38] = file:/home/jw/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
    [ERROR] urls[39] = file:/home/jw/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
    [ERROR] urls[40] = file:/home/jw/.m2/repository/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
    [ERROR] urls[41] = file:/home/jw/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.36/jcl-over-slf4j-1.7.36.jar
    [ERROR] urls[42] = file:/home/jw/.m2/repository/org/sonatype/spice/zapper/spice-zapper/1.3/spice-zapper-1.3.jar
    [ERROR] urls[43] = file:/home/jw/.m2/repository/org/fusesource/hawtbuf/hawtbuf-proto/1.9/hawtbuf-proto-1.9.jar
    [ERROR] urls[44] = file:/home/jw/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.9/hawtbuf-1.9.jar
    [ERROR] urls[45] = file:/home/jw/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.jar
    [ERROR] urls[46] = file:/home/jw/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.15/plexus-interpolation-1.15.jar
    [ERROR] urls[47] = file:/home/jw/.m2/repository/ch/qos/logback/logback-core/1.2.10/logback-core-1.2.10.jar
    [ERROR] urls[48] = file:/home/jw/.m2/repository/ch/qos/logback/logback-classic/1.2.10/logback-classic-1.2.10.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

Any ideas?

**Comment by dheid** [comment]
@jamesward Seems like a Java and Maven version issue. Which Maven and Java version do you use?

**Comment by dheid** [comment]
Let's just downgrade Maven Nexus Staging Plugin 1.6.11 back to 1.6.8 for now. There's some incompatibility with Guava.

**Comment by dheid** [comment]
@jamesward Please see https://github.com/webjars/webjars-locator-core/pull/53

**Pull request merged**
